# Generated by Django 4.0.3 on 2024-01-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schedule_bus_alter_schedule_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bus'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart_location', to='api.location'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='api.location'),
        ),
    ]
