# Generated by Django 4.0.3 on 2024-01-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_schedule_bus_alter_schedule_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.booking'),
        ),
    ]
